### PR TITLE
Fix: explicitly cast to uint32_t to mitigate endian-ness problems

### LINKED ISSUE #70: test_cjose_concatkdf_derive_* fail on big endian architectures (s390x, powerpc, ppc64, sparc64, ...)
The tests `test_cjose_concatkdf_derive_*` fail on big endian architectures like s390x, powerpc, ppc64, sparc64, ...:
```
check_concatkdf.c:159:F:concatkdf:test_cjose_concatkdf_derive_simple:0: Assertion 'derived==expected' failed: keylen==%, derived==0x20, expected==0x566eb950
check_concatkdf.c:190:F:concatkdf:test_cjose_concatkdf_derive_ikm:0: Assertion 'derived==expected' failed: keylen==%, derived==0x20, expected==0x566ebb80
check_concatkdf.c:224:F:concatkdf:test_cjose_concatkdf_derive_moreinfo:0: Assertion 'derived==expected' failed: keylen==%, derived==0x20, expected==0x566ebd50
```

Maybe this is something similar to #38 where some bad casts were the source of the problem that go unnoticed on little endian, but make it fail on big endian.
However, I did not find something at a quick glance (except from the fact that `&err` gets used in both function calls there, is not nulled inbetween and is not checked - maybe that would help debugging).

https://github.com/cisco/cjose/blob/1250eff10fa178937aea1924887d114c8ba943c2/test/check_concatkdf.c#L149-L150

More details and complete build logs can be found on the respective Debian Buildd page:
https://buildd.debian.org/status/package.php?p=cjose

There is also a Debian bug report tracking the issue:
https://bugs.debian.org/890907

### PR DESCRIPTION
**Pull request by linuxwolf**
Resolves #70  (hopefully)

### CODE REVIEW

**Comment by moschlar** [comment]
I'm just now testing this patch! ;-)

**Comment by moschlar** [comment]
I'm just now testing this patch! ;-)

**Comment by linuxwolf** [comment]
I guess I was hopeful but doubtful.  I'm not sure what I can do here without access to a big-endian environment.  It will take me a while to figure out a plan.

**Comment by zandbelt** [comment]
I believe this one's obsolete now with #78 being merged.

**Pull request merged**
